/**
 * Project domain entity — bilingual case study matching frontend IProject.
 * No Prisma / ORM types here; infrastructure maps persistence rows.
 */

export type ProjectEntity = {
  id: string;
  titleFr: string;
  titleEn: string;
  descriptionFr: string;
  descriptionEn: string;
  fullDescriptionFr: string | null;
  fullDescriptionEn: string | null;
  problemFr: string;
  problemEn: string;
  solutionFr: string[];
  solutionEn: string[];
  solutionsFr: string[];
  solutionsEn: string[];
  challengesFr: string[];
  challengesEn: string[];
  impactFr: string[];
  impactEn: string[];
  resultsFr: string[];
  resultsEn: string[];
  metrics: unknown;
  techStack: unknown;
  architecture: string[];
  testing: string[];
  images: string[];
  preview: string;
  videoDemo: string | null;
  category: string;
  status: string;
  complexity: string;
  role: string;
  teamSize: number | null;
  duration: string;
  date: string;
  github: string | null;
  demo: string | null;
  caseStudy: string | null;
  documentation: string | null;
  businessContextFr: string | null;
  businessContextEn: string | null;
  isFeatured: boolean;
  isPublished: boolean;
  confidential: boolean;
  responsibilitiesFr: string[];
  responsibilitiesEn: string[];
  videos: unknown;
  gallery: unknown;
  diagrams: unknown;
  resources: unknown;
  milestones: unknown;
  scopeFr: string[];
  scopeEn: string[];
  nonGoalsFr: string[];
  nonGoalsEn: string[];
  decisions: unknown;
  securityFr: string[];
  securityEn: string[];
  infraFr: string[];
  infraEn: string[];
  externalLinks: unknown;
  testimonial: unknown;
  lessonsFr: string[];
  lessonsEn: string[];
  beforeAfter: unknown;
  sortOrder: number;
  ownerId: string | null;
  createdAt: Date;
  updatedAt: Date;
  deletedAt: Date | null;
};

export type CreateProjectInput = {
  titleFr: string;
  titleEn: string;
  descriptionFr: string;
  descriptionEn: string;
  fullDescriptionFr?: string | null;
  fullDescriptionEn?: string | null;
  problemFr: string;
  problemEn: string;
  solutionFr: string[];
  solutionEn: string[];
  solutionsFr?: string[];
  solutionsEn?: string[];
  challengesFr?: string[];
  challengesEn?: string[];
  impactFr: string[];
  impactEn: string[];
  resultsFr?: string[];
  resultsEn?: string[];
  metrics?: unknown;
  techStack: unknown;
  architecture?: string[];
  testing?: string[];
  images: string[];
  preview: string;
  videoDemo?: string | null;
  category: string;
  status: string;
  complexity: string;
  role: string;
  teamSize?: number | null;
  duration: string;
  date: string;
  github?: string | null;
  demo?: string | null;
  caseStudy?: string | null;
  documentation?: string | null;
  businessContextFr?: string | null;
  businessContextEn?: string | null;
  isFeatured?: boolean;
  isPublished?: boolean;
  confidential?: boolean;
  responsibilitiesFr?: string[];
  responsibilitiesEn?: string[];
  videos?: unknown;
  gallery?: unknown;
  diagrams?: unknown;
  resources?: unknown;
  milestones?: unknown;
  scopeFr?: string[];
  scopeEn?: string[];
  nonGoalsFr?: string[];
  nonGoalsEn?: string[];
  decisions?: unknown;
  securityFr?: string[];
  securityEn?: string[];
  infraFr?: string[];
  infraEn?: string[];
  externalLinks?: unknown;
  testimonial?: unknown;
  lessonsFr?: string[];
  lessonsEn?: string[];
  beforeAfter?: unknown;
  sortOrder?: number;
  ownerId: string;
};

export type UpdateProjectInput = Partial<{
  titleFr: string;
  titleEn: string;
  descriptionFr: string;
  descriptionEn: string;
  fullDescriptionFr: string | null;
  fullDescriptionEn: string | null;
  problemFr: string;
  problemEn: string;
  solutionFr: string[];
  solutionEn: string[];
  solutionsFr: string[];
  solutionsEn: string[];
  challengesFr: string[];
  challengesEn: string[];
  impactFr: string[];
  impactEn: string[];
  resultsFr: string[];
  resultsEn: string[];
  metrics: unknown;
  techStack: unknown;
  architecture: string[];
  testing: string[];
  images: string[];
  preview: string;
  videoDemo: string | null;
  category: string;
  status: string;
  complexity: string;
  role: string;
  teamSize: number | null;
  duration: string;
  date: string;
  github: string | null;
  demo: string | null;
  caseStudy: string | null;
  documentation: string | null;
  businessContextFr: string | null;
  businessContextEn: string | null;
  isFeatured: boolean;
  isPublished: boolean;
  confidential: boolean;
  responsibilitiesFr: string[];
  responsibilitiesEn: string[];
  videos: unknown;
  gallery: unknown;
  diagrams: unknown;
  resources: unknown;
  milestones: unknown;
  scopeFr: string[];
  scopeEn: string[];
  nonGoalsFr: string[];
  nonGoalsEn: string[];
  decisions: unknown;
  securityFr: string[];
  securityEn: string[];
  infraFr: string[];
  infraEn: string[];
  externalLinks: unknown;
  testimonial: unknown;
  lessonsFr: string[];
  lessonsEn: string[];
  beforeAfter: unknown;
  sortOrder: number;
  deletedAt: Date | null;
}>;

export type ProjectListFilters = {
  page: number;
  limit: number;
  isPublished?: boolean;
  isFeatured?: boolean;
  category?: string;
};

export type ProjectListResult = {
  items: ProjectEntity[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
};
