import type { Project as PrismaProject } from '@prisma/client';

import type { ProjectEntity } from '../../domain/entities/project.entity';

/**
 * Maps Prisma Project rows ↔ domain ProjectEntity.
 */
export const ProjectMapper = {
  toDomain(row: PrismaProject): ProjectEntity {
    return {
      id: row.id,
      titleFr: row.titleFr,
      titleEn: row.titleEn,
      descriptionFr: row.descriptionFr,
      descriptionEn: row.descriptionEn,
      fullDescriptionFr: row.fullDescriptionFr ?? null,
      fullDescriptionEn: row.fullDescriptionEn ?? null,
      problemFr: row.problemFr,
      problemEn: row.problemEn,
      solutionFr: row.solutionFr,
      solutionEn: row.solutionEn,
      solutionsFr: row.solutionsFr,
      solutionsEn: row.solutionsEn,
      challengesFr: row.challengesFr,
      challengesEn: row.challengesEn,
      impactFr: row.impactFr,
      impactEn: row.impactEn,
      resultsFr: row.resultsFr,
      resultsEn: row.resultsEn,
      metrics: row.metrics ?? null,
      techStack: row.techStack,
      architecture: row.architecture,
      testing: row.testing,
      images: row.images,
      preview: row.preview,
      videoDemo: row.videoDemo ?? null,
      category: row.category,
      status: row.status,
      complexity: row.complexity,
      role: row.role,
      teamSize: row.teamSize ?? null,
      duration: row.duration,
      date: row.date,
      github: row.github ?? null,
      demo: row.demo ?? null,
      caseStudy: row.caseStudy ?? null,
      documentation: row.documentation ?? null,
      businessContextFr: row.businessContextFr ?? null,
      businessContextEn: row.businessContextEn ?? null,
      isFeatured: row.isFeatured,
      isPublished: row.isPublished,
      confidential: row.confidential,
      responsibilitiesFr: row.responsibilitiesFr,
      responsibilitiesEn: row.responsibilitiesEn,
      videos: row.videos ?? null,
      gallery: row.gallery ?? null,
      diagrams: row.diagrams ?? null,
      resources: row.resources ?? null,
      milestones: row.milestones ?? null,
      scopeFr: row.scopeFr,
      scopeEn: row.scopeEn,
      nonGoalsFr: row.nonGoalsFr,
      nonGoalsEn: row.nonGoalsEn,
      decisions: row.decisions ?? null,
      securityFr: row.securityFr,
      securityEn: row.securityEn,
      infraFr: row.infraFr,
      infraEn: row.infraEn,
      externalLinks: row.externalLinks ?? null,
      testimonial: row.testimonial ?? null,
      lessonsFr: row.lessonsFr,
      lessonsEn: row.lessonsEn,
      beforeAfter: row.beforeAfter ?? null,
      sortOrder: row.sortOrder,
      ownerId: row.ownerId ?? null,
      createdAt: row.createdAt,
      updatedAt: row.updatedAt,
      deletedAt: row.deletedAt ?? null,
    };
  },
};
